#tasks file for apache
- import_tasks: install.yml
  when: ansible_distribution_file_variety == "RedHat"
- import_tasks: install_debian.yml
  when: ansible_distribution_file_variety == "Debian"


- import_tasks: configure.yml
- import_tasks: service.yml

