---
- name: Les blocs dans anisble
  hosts: webservers
  tasks:
  - name: Install, configure, and start Apache
    block:
    - name: Install httpd and memcached
      yum:
        name:
        - httpd22
        - memcached
        state: present

    - name: Apply the config template
      template:
        src: templates/httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf

    - name: Start service bar and enable it
      service:
        name: httpd
        state: started
        enabled: True
    rescue:
    - name: Notification an cas de problème
      debug: msg="Il ya un problème dans l'une des tâches exécutées dans le bloc"
    always:
    - name: Fin d'exécution
      debug: msg="Fin d'exécution du bloc dans ce playbook"
    when: ansible_facts['distribution'] == 'CentOS'
    become: true

